
package calculator.business.calculation.webservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "CalculationWebServiceException", targetNamespace = "http://webservice.calculation.business.calculator/")
public class CalculationWebServiceException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private CalculationWebServiceException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public CalculationWebServiceException_Exception(String message, CalculationWebServiceException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public CalculationWebServiceException_Exception(String message, CalculationWebServiceException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: calculator.business.calculation.webservice.CalculationWebServiceException
     */
    public CalculationWebServiceException getFaultInfo() {
        return faultInfo;
    }

}
