
package calculator.ui.webservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "CalculationServiceException", targetNamespace = "http://webservice.ui.calculator/")
public class CalculationServiceException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private CalculationServiceException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public CalculationServiceException_Exception(String message, CalculationServiceException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public CalculationServiceException_Exception(String message, CalculationServiceException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: calculator.ui.webservice.CalculationServiceException
     */
    public CalculationServiceException getFaultInfo() {
        return faultInfo;
    }

}
