
package calculator.ui.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WebServiceCalculation", targetNamespace = "http://webservice.ui.calculator/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebServiceCalculation {


    /**
     * 
     * @return
     *     returns calculator.ui.webservice.Calculation
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCalculation", targetNamespace = "http://webservice.ui.calculator/", className = "calculator.ui.webservice.GetCalculation")
    @ResponseWrapper(localName = "getCalculationResponse", targetNamespace = "http://webservice.ui.calculator/", className = "calculator.ui.webservice.GetCalculationResponse")
    public Calculation getCalculation();

    /**
     * 
     * @param calculation
     * @return
     *     returns calculator.ui.webservice.Calculation
     * @throws CalculationServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "solveCalculation", targetNamespace = "http://webservice.ui.calculator/", className = "calculator.ui.webservice.SolveCalculation")
    @ResponseWrapper(localName = "solveCalculationResponse", targetNamespace = "http://webservice.ui.calculator/", className = "calculator.ui.webservice.SolveCalculationResponse")
    public Calculation solveCalculation(
        @WebParam(name = "calculation", targetNamespace = "")
        Calculation calculation)
        throws CalculationServiceException_Exception
    ;

}
